run:
	python send_updates.py
	python view_csv.py
	python daily_leaders.py
	python email_updater.py $(arg1) $(arg2)

html_and_run:
	python send_updates.py
	python view_csv.py
	python daily_leaders.py

just_html:
	python view_csv.py
	python daily_leaders.py

all:
	python send_updates.py
	python view_csv.py
	python daily_leaders.py
	python email_updater.py travisjohnson0325@gmail.com ivctrmzuifdgibvz